# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_tergo_wrappers", use_symbols = TRUE, package_name = "tergo")

#' @usage NULL
#' @useDynLib tergo, .registration = TRUE
NULL

#' Format code
#'
#' @param source_code (`character`) the R code to format
#'
#' @return (`character`) the formatted code
#' @keywords internal
format_code <- function(source_code, configuration) .Call(wrap__format_code, source_code, configuration)

#' Parse the config file and return the configuration
#'
#' @param path (`character(1)`) the file path of the configuration
#' file
#'
#' @return (`list`)
#' @keywords internal
get_config <- function(path) .Call(wrap__get_config, path)

#' Get the default configuration
#'
#' @return `list` with the default configuration
#' @keywords internal
get_default_config <- function() .Call(wrap__get_default_config)


# nolint end
