[package]
name = "scopa"
version = "0.1.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]
path = "./src/lib.rs"

[dependencies]
wit-bindgen = "0.32.0"
tergo-lib = { path = "../balnea", version = "0.2.10" }

[dev-dependencies]
wasm-tools = "1.217.0"
