[package]
name = "tergo"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]
name = "tergo"

[dependencies]
tergo-lib = "0.2.5"
toml = "0.8.19"
extendr-api = "*"

[workspace]
exclude = ["vendor", "repo_vendor"]
