name: Rust

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "antidotum"
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "antidotum"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Update Rust build tools
        run: |
          rustup update
      - name: Build
        run: cargo build --verbose --release
      - name: Run tests
        run: cargo test --verbose --release
